### ISSUE TITLE
Linux Support!

### ISSUE THREAD

**Issue by luiscachog** [esthor/overcast-electron-app-mac#2]
+1 on Linux flavor!

**Comment by esthor** [comment]
We now have a linux version! https://github.com/esthor/overcast-electron-app-mac/tree/master/overcast-linux-x64

Please let me know if you have any problems with it, otherwise I will close this soon 😄

**Comment by luiscachog** [comment]
Cool! I will try it!!

**Comment by luiscachog** [comment]
After tried I received the error:

symbol lookup error: /home/luis7238/overcast-electron-app-mac/overcast-linux-x64/overcast: undefined symbol: udata_setCommonData_59

**Comment by luiscachog** [comment]
Still not working ... :S

**Comment by esthor** [comment]
@k4ch0 what linux distro are you on?

**Comment by esthor** [comment]
I think if you follow these instructions, it should work, at least if you're on an ubuntu-based distro...

    Download/clone the overcast-linux-x64
    `cd` into the folder
    Run `sudo chhmod +x *` in the folder (this updates the permissions so the app can run)
    Then just run `./overcast` in the folder. Voila!

I've added these to the main README as well.

**Comment by luiscachog** [comment]
Hi @esthor!

Sorry, but for me, it is still not working, even if I follow up on the steps that you provide.

```
/home/luis7238/overcast-electron-app/overcast-linux-x64/overcast: symbol lookup error: /home/luis7238/overcast-electron-app/overcast-linux-x64/overcast: undefined symbol: udata_setCommonData_59
```
Also, I'm using Linux Mint 19, based on Ubuntu 18.04.

**Comment by esthor** [comment]
hey @k4ch0 I was able to repro your error! Woo!

I think I might have a real solution this time... try downloading the new `overcast-linx-x64.zip` file and following the updated instructions:

```
    Download overcast-linux-x64.zip && extract the files
    cd into the extracted folder
    Run sudo chhmod +x * in the folder (this updates the permissions so the app can run)
    Then just run ./overcast in the folder. Voila!
```

**Comment by luiscachog** [comment]
Excellent! It is working now!! :)
